### ISSUE TITLE
How do I add an attachment?

### ISSUE THREAD

**Issue by isabellachen** [yutikom/strapi-provider-email-nodemailer#1]
I see that this plugin takes care of attachments,  but where in the strapi admin panel am I suppose to add these attachments? There are no fields available in the email template form...
![image](https://user-images.githubusercontent.com/9280665/61810151-ef72e300-ae3e-11e9-9b0a-4b7b3b8468d7.png)

**Comment by veitbjarsch** [comment]
Hi, attachment currently can't be added via the UI. This plugin provides only a provider. The UI is handled completely by strapi. Nevertheless you can add an attachment if you are calling the mail service programatically from your controller or service. 

```
strapi.plugins['email'].services.email.send({
        to: '',
        from: '',
        replyTo:  '',
        subject:  '',
        text:  '',
        html:  '',
        attachments: [],
      }
```
For more details about the attachments, you can check out https://nodemailer.com/message/attachments/
