### ISSUE TITLE
Support for email templates via sendTemplatedEmail?

### ISSUE THREAD

**Issue by collegewap** [yutikom/strapi-provider-email-nodemailer#16]
The [strapi documentation ](https://strapi.io/documentation/v3.x/plugins/email.html#programmatic-usage) says I can send template-based notification using the `strapi.plugins.email.services.email.sendTemplatedEmail()` function. However when I use this plugin, I get the following error:

`error TypeError: strapi.plugins.email.services.email.sendTemplatedEmail is not a function`

strapi:3.0.5
strapi-provider-email-nodemailer: 3.0.0

**Comment by veitbjarsch** [comment]
Hi, this feature should be supported out of the box. It is part of the main strapi package. You can find the source code here:
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-email/services/Email.js

Our extension only adds the send function, that is used in the file I've mentioned above (strapi.plugins.email.provider.send())

So if there is a problem with the sendTemplatedEmail function, you need to open an issue here: https://github.com/strapi/strapi/issues
