### ISSUE TITLE
version 1.0.3 different code from npm and github attribute config.secure 

### ISSUE THREAD

**Issue by fragzero** [yutikom/strapi-provider-email-nodemailer#2]
Hello,

When I use the `npm i strapi-provider-email-nodemailer` package is downloaded from this url

https://registry.npmjs.org/strapi-provider-email-nodemailer/-/strapi-provider-email-nodemailer-1.0.3.tgz

When try to use `/admin/plugins/users-permissions/auth/forgot-password` from strapi login screen I get error on `/lib/index.js` in this line of code 
```js
52        secure: _.toBool(config.secure),
```
I don't know where I can configure this `config.secure` attribute

![image](https://user-images.githubusercontent.com/3706386/64256436-de1afd00-cef9-11e9-97a0-82ad56129952.png)

But the version 1.0.3 from npm is different code from github
https://github.com/yutikom/strapi-provider-email-nodemailer/blob/master/lib/index.js

I appreciate any help, thanks

**Comment by yutikom** [comment]
Hi,

This param is supported only through the API for now. We don't use Strapi
GUI at all and built own GUI instead.

Regards,
Yurii

ср, 4 сент. 2019 г., 16:02 FragZero <notifications@github.com>:

**Comment by Hokid** [comment]
```
TypeError: _.toBool is not a function
    at Object.init (/mnt/0x1/projects/work/0/api-cms/node_modules/strapi-provider-email-nodemailer/lib/index.js:67:19)
    at Object.send (/mnt/0x1/projects/work/0/api-cms/node_modules/strapi-plugin-email/services/Email.js:57:30)
```

**Comment by mcaulirealt** [comment]
@yutikom npmjs version is not synced with github's one. 
to run installation from github run `npm install github:yutikom/strapi-provider-email-nodemailer`

**Comment by veitbjarsch** [comment]
I'll fix it with the next release.
