### ISSUE TITLE
TypeError: _.toBool is not a function

### ISSUE THREAD

**Issue by ivoba** [yutikom/strapi-provider-email-nodemailer#4]
I get this error when sending a mail:
>TypeError: _.toBool is not a function

Seems that its a lodash version problem since latest lodash doesnt have a toBool function.

Also lodash is not in package.json dependencies.

Can you also tag your versions wit git please :)

**Comment by veitbjarsch** [comment]
#5

**Comment by veitbjarsch** [comment]
This issue will be fixed in the next release: #5
