### ISSUE TITLE
Strapi V3 incompatibility

### ISSUE THREAD

**Issue by roschaefer** [yutikom/strapi-provider-email-nodemailer#9]
As far as I can see, Strapi v3.x changed its API for email providers. This npm package is therefore outdated. Could we please merge back the [v3 compatible fork](https://github.com/Saunved/strapi-provider-email-nodemailer) here and release a new major version?

Also, I just created a PR which allows the user to specify all configurations for `nodemailer.createTransport` here: https://github.com/Saunved/strapi-provider-email-nodemailer/pull/1

I don't understand why the folks at Strapi don't maintain a plain SMTP email provider. Instead they just link to https://www.npmjs.com/search?q=strapi-provider-email- in their current docs: https://strapi.io/documentation/v3.x/plugins/email.html#configure-the-plugin

Since the maintainer of this github repo is maintaining the npm package with the name `strapi-provider-email-nodemailer` which is the most obvious name in my opinion, we should focus on this package instead of creating 3k different forks, right?

Opinions?

**Comment by veitbjarsch** [comment]
Dann it. I don't receive any emails from this repository. You are absolutely correct. Can you create a PR for this change here. I will try my best to check it out on the weekend.

**Comment by OMO-NOSA** [comment]
@roschaefer has this been resolved?

**Comment by veitbjarsch** [comment]
@OMO-NOSA Yeah I had some other problems to solve. Sorry for the delay. I'm currently working on it and hope to release the new version today.

**Comment by veitbjarsch** [comment]
@OMO-NOSA @roschaefer Just released the latest version. The provider is now compatible to Strapi 3.
